//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Batalion.cpp
//  @ Date : 3/30/2023
//  @ Author : 
//
//


#include <iostream>
#include "Batalion.h"

using namespace std;

Batalion::Batalion( int size) {
    for (int i = 0; i < size; ++i) {
        Soldier *soldier = new Soldier();
        soldier->setId(i);
        soldiers.push_back(soldier);
    }

}

Batalion::~Batalion() {
    soldiers.clear();
    //delete soldiers;
}

void Batalion::setBtNumber(int BtNumber) {
    this->BtNumber = BtNumber;
}

int Batalion::getBtNumber() {
    return  BtNumber;
}

void Batalion::setData(string name, string rank, int id) {
    if(id > soldiers.size())
    {
        cout << "Wrong id" << endl;
    } else{
        soldiers[id]->setName(name);
        soldiers[id]->setRank(rank);
    }
}

void Batalion::getData(int id) {
    if(id > soldiers.size())
    {
        cout << "Wrong id" << endl;
    } else{
        cout << soldiers[id]->getName() << " " << soldiers[id]->getRank() << endl;
    }
}

Soldier* Batalion::getSoldier(int id) {
    if(id > soldiers.size())
    {
        cout << "Wrong id" << endl;
    } else{
        return soldiers[id];
    }
}
