//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Commander.h
//  @ Date : 3/30/2023
//  @ Author : 
//
//


#if !defined(_COMMANDER_H)
#define _COMMANDER_H

#include "Soldier.h"

class Commander {
public:
	void Promote(Soldier soldier, string rank);
	string getName();
	void setName(string name);
	void giveOrder(string order);
private:
	string name;
};

#endif  //_COMMANDER_H
