//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Commander.cpp
//  @ Date : 3/30/2023
//  @ Author : 
//
//


#include <iostream>
#include "Commander.h"
#include "Soldier.h"

void Commander::Promote(Soldier soldier, string rank) {
    soldier.setRank(rank);
   cout << "Promoted to " << soldier.getRank() << endl;
}

string Commander::getName() {
    return name;
}

void Commander::setName(string name) {
    this->name = name;
}

void Commander::giveOrder(string order) {
    cout << "An order to " << order << "has been given";
}

