//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Soldier.h
//  @ Date : 3/30/2023
//  @ Author : 
//
//


#if !defined(_SOLDIER_H)
#define _SOLDIER_H
#include <string>

using namespace std;

class Soldier {
public:
	Soldier();
	~Soldier();
	void setName(string name);
	string getName();
	void setRank(string rank);
	string getRank();
	void setId(int id);
	int getId();
    void patrol();
    void defendArea();
private:
	string name;
	string rank;
	int id;
};

#endif  //_SOLDIER_H
