//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Soldier.cpp
//  @ Date : 3/30/2023
//  @ Author : 
//
//


#include <iostream>
#include "Soldier.h"

using namespace std;

Soldier::Soldier() {

}

Soldier::~Soldier() {

}

void Soldier::setName(string name) {
    this->name = name;
}

string Soldier::getName() {
    return name;
}

void Soldier::setRank(string rank) {
    this->rank = rank;
}

string Soldier::getRank() {
    return rank;
}

void Soldier::setId(int id) {
    this->id = id;
}

int Soldier::getId() {
    return  id;
}

void Soldier::patrol() {
    cout << "The soldier is patrolling" << endl;
}

void Soldier::defendArea() {
    cout << "The soldier is defending an area" << endl;
}
